name: sfefef
description: ''
version: 1.0.1
author: ''
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: sfefef
  parentArtefactID: simpledatalabs_27
  buildSystem: maven
  author: null
  createdAt: '2023-02-28 11:47:08'
  modifiedAt: '2023-02-28 11:47:08'
pipelines:
  pipelines/deed:
    name: deed
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-03-22 11:10:32'
    modifiedAt: '2023-03-23 08:26:07'
    datasets:
      inputs:
      - datasets/de
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/frfrf:
    name: frfrf
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-03-23 07:52:15'
    modifiedAt: '2023-03-23 08:25:25'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/normalization:
    name: normalization
    description: ''
    author: rohitjain+27@simpledatalabs.com
    createdAt: '2023-03-20 10:17:32'
    modifiedAt: '2023-03-20 12:36:26'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 52
        datasetType: File
        description: ''
        author: rohitjain+27@simpledatalabs.com
        createdAt: '2023-03-20 10:17:32'
        modifiedAt: '2023-03-20 10:17:32'
  datasets/normalization_out:
    name: normalization_out
    description: ''
    author: rohitjain+27@simpledatalabs.com
    createdAt: '2023-03-20 10:41:44'
    modifiedAt: '2023-03-20 14:23:45'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 52
        datasetType: File
        description: ''
        author: rohitjain+27@simpledatalabs.com
        createdAt: '2023-03-20 10:41:44'
        modifiedAt: '2023-03-20 10:41:44'
  datasets/de:
    name: de
    description: ''
    author: rohitjain+27@simpledatalabs.com
    createdAt: '2023-03-23 05:57:40'
    modifiedAt: '2023-03-23 05:57:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 52
        datasetType: File
        description: ''
        author: rohitjain+27@simpledatalabs.com
        createdAt: '2023-03-23 05:57:40'
        modifiedAt: '2023-03-23 05:57:40'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-02-28 11:47:08'
  modifiedAt: '2023-03-23 08:26:07'
  gems: {}
  udfs:
    udfs/matrix_col_count:
      name: matrix_col_count
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
    udfs/generate_matrix:
      name: generate_matrix
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
    udfs/generate_vector:
      name: generate_vector
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
    udfs/udf3:
      name: udf3
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
    udfs/udf4:
      name: udf4
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
    udfs/udf2:
      name: udf2
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
