name: ExternalGitProject
description: ''
version: 0.0.1-SNAPSHOT
author: rohitjain+27@simpledatalabs.com
language: scala
buildSystem: maven
pipelines:
  pipelines/Application1:
    name: Application1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-11-17 10:20:33'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/9CnRzp7s_team_95/HjDoIqdC_project_182.git&subPath=&tag=ApplicationProject2/1.0&projectSubscriptionProjectId=182&path=datasets/ApplicationDS1
      - gitUri=http://gitserver:3000/aH3lOJfD_team_93/gq7R5qIv_project_177.git&subPath=&tag=BaseProjectScala/8.0&projectSubscriptionProjectId=177&path=datasets/baseDS1
      - gitUri=http://gitserver:3000/aH3lOJfD_team_93/gq7R5qIv_project_177.git&subPath=&tag=BaseProjectScala/8.0&projectSubscriptionProjectId=177&path=datasets/baseDS3
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '182':
    projectUID: 182
    projectName: ApplicationProject2
    repositoryPath: gitUri=http://gitserver:3000/9CnRzp7s_team_95/HjDoIqdC_project_182.git&subPath=
    version: ApplicationProject2/1.0
    author: ''
    createdAt: '2022-11-17 11:39:14'
  '177':
    projectUID: 177
    projectName: BaseProjectScala
    repositoryPath: gitUri=http://gitserver:3000/aH3lOJfD_team_93/gq7R5qIv_project_177.git&subPath=
    version: BaseProjectScala/8.0
    author: ''
    createdAt: '2022-11-17 11:39:14'
pipelineConfigurations: {}
