name: ScalaGemsMigrationExamples
description: ''
version: '1.0'
author: rohitjain@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: scalagemsmigrationexamples
  parentArtefactID: rohitjainprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2023-12-21 09:57:13'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: rohitjain@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-12-21 09:59:22'
    datasets:
      inputs:
      - datasets/ds1
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/ds1:
    name: ds1
    description: ''
    author: rohitjain@prophecy.io
    createdAt: '2023-12-21 10:00:27'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1
        datasetType: File
        description: ''
        author: rohitjain@prophecy.io
        createdAt: '2023-12-21 10:00:27'
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.0.10.1-gem-migration-SNAPSHOT
  gems:
    gems/ReformatCustom:
      name: ReformatCustom
      category: Transform
      subCategory: ''
      description: null
      author: rohitjain@prophecy.io
      mode: batch
      files:
      - src/main/scala/rohitjainprophecyioteam/scalagemsmigrationexamples/gems/ReformatCustom.scala
      dependencies: []
      createdAt: '2023-12-21 10:00:38'
  dependencies: null
functions:
  author: null
  createdAt: '2023-12-21 09:57:13'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '10':
    projectUID: 10
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/zRRrTuoN_team_5/b9ewggAW_project_10.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2023-12-21 09:56:15'
  '9':
    projectUID: 9
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/zRRrTuoN_team_5/b9ewggAW_project_9.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2023-12-21 09:56:15'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
