name: PM3ReWork
description: ''
version: '2.0'
author: rohitjain+27@simpledatalabs.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: pm3rework
  parentArtefactID: rohitjain27simpledatalabs.com_team
  buildSystem: maven
  author: null
  createdAt: '2023-03-01 07:05:28'
  modifiedAt: '2023-03-01 07:05:28'
pipelines:
  pipelines/pipeline1:
    name: pipeline1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-02-20 06:56:19'
    modifiedAt: '2023-03-13 10:05:07'
    datasets:
      inputs:
      - datasets/ds1
      - gitUri=http://gitserver:3000/FbAJ3f4S_team_92/2E6pIkqi_project_263.git&subPath=&tag=baseProjectRW2/1.0&projectSubscriptionProjectId=263&path=datasets/baseprojectrw2ds1
      - gitUri=https://github.com/aarjay00/prophecyTest&subPath=/baseProjectRW&tag=BaseProjectRW/36.0&projectSubscriptionProjectId=228&path=datasets/baseDS1
      outputs: []
    subgraphs:
    - subgraphs/sg1
    dependencies: {}
  pipelines/pipeline2:
    name: pipeline2
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-02-27 14:41:11'
    modifiedAt: '2023-03-01 07:10:00'
    datasets:
      inputs:
      - datasets/ds1
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pipeline3:
    name: pipeline3
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-02-27 14:42:40'
    modifiedAt: '2023-03-01 07:10:30'
    datasets:
      inputs:
      - datasets/ds1
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/ds1:
    name: ds1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    createdAt: '2023-02-20 06:59:58'
    modifiedAt: '2023-03-01 06:14:11'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 52
        datasetType: File
        description: ''
        author: rohitjain+27@simpledatalabs.com
        createdAt: '2023-02-20 06:59:58'
        modifiedAt: '2023-02-20 06:59:58'
templates: {}
jobs:
  jobs/appJob1:
    name: appJob1
    description: ''
    fabricUID: 52
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/pipeline1
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-02-20 12:54:12'
    modifiedAt: '2023-02-20 12:54:12'
    author: rohitjain+27@simpledatalabs.com
functions:
  author: null
  createdAt: '2023-03-01 07:05:28'
  modifiedAt: '2023-03-13 10:05:07'
  gems: {}
  udfs:
    udfs/trimUDF4:
      name: trimUDF4
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
    udfs/trimUDF1:
      name: trimUDF1
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
    udfs/trimUDF2:
      name: trimUDF2
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
    udfs/trimUDF3:
      name: trimUDF3
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
    udfs/trimUDF5:
      name: trimUDF5
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/sg1:
    name: sg1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    language: scala
    artefactID: ''
    mode: batch
    createdAt: '2023-02-20 07:00:29'
    modifiedAt: '2023-03-13 06:31:00'
sqlModels: {}
sqlPipeline: null
dependencies:
- type: coordinates
  coordinates: org.apache.commons:commons-lang3:3.11
  name: commons
  enabled: false
  id: EDPzF
  exclusions: []
projectDependencies:
  '228':
    projectUID: 228
    projectName: BaseProjectRW
    repositoryPath: gitUri=https://github.com/aarjay00/prophecyTest&subPath=/baseProjectRW
    version: BaseProjectRW/36.0
    author: null
    createdAt: '2023-03-08 08:51:38'
    modifiedAt: '2023-03-08 08:51:38'
  '263':
    projectUID: 263
    projectName: baseProjectRW2
    repositoryPath: gitUri=http://gitserver:3000/FbAJ3f4S_team_92/2E6pIkqi_project_263.git&subPath=
    version: baseProjectRW2/1.0
    author: null
    createdAt: '2023-03-08 08:55:33'
    modifiedAt: '2023-03-08 08:55:33'
pipelineConfigurations: {}
