name: PM3ReWork
description: ''
version: '2.0'
author: rohitjain+27@simpledatalabs.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: pm3rework
  parentArtefactID: rohitjain27simpledatalabs.com_team
  buildSystem: maven
  author: null
  createdAt: '2023-03-14 08:28:42'
  modifiedAt: '2023-03-14 08:28:42'
pipelines:
  pipelines/pipeline1:
    name: pipeline1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-02-20 06:56:19'
    modifiedAt: '2023-05-24 10:45:44'
    datasets:
      inputs:
      - datasets/ds1
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pipeline2:
    name: pipeline2
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-02-27 14:41:11'
    modifiedAt: '2023-04-03 15:19:48'
    datasets:
      inputs:
      - datasets/ds1
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pipeline3:
    name: pipeline3
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-02-27 14:42:40'
    modifiedAt: '2023-04-03 15:19:50'
    datasets:
      inputs:
      - datasets/ds1
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/kaajri12312:
    name: kaajri12312
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-03-27 14:42:15'
    modifiedAt: '2023-04-03 15:04:43'
    datasets:
      inputs:
      - datasets/ds1
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/ds1:
    name: ds1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    createdAt: '2023-02-20 06:59:58'
    modifiedAt: '2023-03-01 06:14:11'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 52
        datasetType: File
        description: ''
        author: rohitjain+27@simpledatalabs.com
        createdAt: '2023-02-20 06:59:58'
        modifiedAt: '2023-02-20 06:59:58'
templates: {}
jobs:
  jobs/appJob1:
    name: appJob1
    description: ''
    fabricUID: 52
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/pipeline1
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-02-20 12:54:12'
    modifiedAt: '2023-03-27 11:56:10'
    author: rohitjain+27@simpledatalabs.com
functions:
  author: null
  createdAt: '2023-03-14 08:28:42'
  modifiedAt: '2023-03-27 15:01:37'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/sg1:
    name: sg1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    language: scala
    artefactID: ''
    mode: batch
    createdAt: '2023-02-20 07:00:29'
    modifiedAt: '2023-03-01 06:13:18'
  subgraphs/sdfsd:
    name: sdfsd
    description: fsd
    author: rohitjain+27@simpledatalabs.com
    language: scala
    artefactID: ''
    mode: batch
    createdAt: '2023-03-27 14:40:11'
    modifiedAt: '2023-03-27 14:40:11'
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: coordinates
  coordinates: org.apache.commons:commons-lang3:3.11
  name: commons
  enabled: false
  id: EDPzF
  exclusions: []
projectDependencies:
  '228':
    projectUID: 228
    projectName: BaseProjectRW
    repositoryPath: gitUri=https://github.com/aarjay00/prophecyTest&subPath=/baseProjectRW
    version: BaseProjectRW/37.0
    author: null
    createdAt: '2023-03-27 14:44:25'
    modifiedAt: '2023-03-27 14:44:25'
  '21759':
    projectUID: 21759
    projectName: BaseProjectRW
    repositoryPath: gitUri=https://github.com/aarjay00/prophecyTest&subPath=/baseProjectRW
    version: BaseProjectRW/110.0
    author: null
    createdAt: '2023-03-27 15:01:21'
    modifiedAt: '2023-03-27 15:01:21'
pipelineConfigurations: {}
