name: PM3ReWork
description: ''
version: '1.0'
author: rohitjain+27@simpledatalabs.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: pm3rework
  parentArtefactID: rohitjain27simpledatalabs.com_team
  buildSystem: maven
  author: null
  createdAt: '2023-02-27 10:56:46'
  modifiedAt: '2023-02-27 10:56:46'
pipelines:
  pipelines/pipeline1:
    name: pipeline1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-02-20 06:56:19'
    modifiedAt: '2023-02-27 13:51:19'
    datasets:
      inputs:
      - datasets/ds1
      outputs: []
    subgraphs:
    - subgraphs/sg1
    dependencies: {}
datasets:
  datasets/ds1:
    name: ds1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    createdAt: '2023-02-20 06:59:58'
    modifiedAt: '2023-02-20 06:59:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 52
        datasetType: File
        description: ''
        author: rohitjain+27@simpledatalabs.com
        createdAt: '2023-02-20 06:59:58'
        modifiedAt: '2023-02-20 06:59:58'
templates: {}
jobs:
  jobs/appJob1:
    name: appJob1
    description: ''
    fabricUID: 52
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - gitUri=https://github.com/aarjay00/prophecyTest&subPath=/baseProjectRW&tag=BaseProjectRW/7.0&projectSubscriptionProjectId=228&path=pipelines/basePipeline1
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-02-20 12:54:12'
    modifiedAt: '2023-02-20 12:54:12'
    author: rohitjain+27@simpledatalabs.com
functions:
  author: null
  createdAt: '2023-02-20 06:55:59'
  modifiedAt: '2023-02-27 13:51:19'
  gems: {}
  udfs:
    udfs/trim:
      name: trimUDF
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2023-02-20 07:44:41'
      modifiedAt: '2023-02-20 07:44:41'
    udfs/square:
      name: square
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2023-02-20 07:44:41'
      modifiedAt: '2023-02-20 07:44:41'
    udfs/square2:
      name: square212
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2023-02-23 07:25:01'
      modifiedAt: '2023-02-23 07:25:01'
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/sg1:
    name: sg1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    language: scala
    artefactID: ''
    mode: batch
    createdAt: '2023-02-20 07:00:29'
    modifiedAt: '2023-02-27 13:51:19'
sqlModels: {}
sqlPipeline: null
dependencies:
- type: coordinates
  coordinates: org.apache.commons:commons-lang3:3.12.0
  name: commons
  enabled: false
  id: EDPzF
  exclusions: []
projectDependencies:
  '228':
    projectUID: 228
    projectName: BaseProjectRW
    repositoryPath: gitUri=https://github.com/aarjay00/prophecyTest&subPath=/baseProjectRW
    version: BaseProjectRW/7.0
    author: null
    createdAt: '2023-02-27 11:05:52'
    modifiedAt: '2023-02-27 11:05:52'
pipelineConfigurations:
  pipelineConfigurations/BaseProjectRW/basePipeline1:
    author: rohitjain+27@simpledatalabs.com
    createdAt: '2023-02-21 12:19:47'
    modifiedAt: '2023-02-21 12:19:47'
    configurations:
      pipelineConfigurations/BaseProjectRW/basePipeline1/default:
        name: default
        author: null
        createdAt: '2023-02-21 12:19:47'
        modifiedAt: '2023-02-27 10:56:46'
      pipelineConfigurations/BaseProjectRW/basePipeline1/dev:
        name: dev
        author: null
        createdAt: '2023-02-21 12:19:48'
        modifiedAt: '2023-02-27 10:56:46'
    basePipeline: 228/pipelines/basePipeline1
