name: BaseProjectExt3
description: dev
version: '2.0'
author: rohitjain+25@simpledatalabs.com
language: scala
buildSystem: ''
buildSystemDetails:
  packageName: BaseProjectExt3
  buildSystem: maven
  author: null
  createdAt: '2022-12-15 18:10:40'
pipelines:
  pipelines/baseP:
    name: baseP
    description: ''
    author: rohitjain+25@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2022-12-15 18:11:16'
    datasets:
      inputs:
      - datasets/sd1
      outputs: []
    subgraphs:
    - subgraphs/sharedSG1
    dependencies: {}
datasets:
  datasets/sd1:
    name: sd1
    description: ''
    author: rohitjain+25@simpledatalabs.com
    createdAt: '2022-12-15 18:11:41'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: rohitjain+25@simpledatalabs.com
        createdAt: '2022-12-15 18:11:41'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2022-12-15 18:10:40'
  gems: {}
  udfs:
    udfs/sharedSquare:
      name: sharedSquare
      description: ''
      tags:
      - ''
      inputs:
      - ''
      outputs:
      - ''
      author: rohitjain+25@simpledatalabs.com
      createdAt: '2022-12-15 18:12:08'
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/sharedSG1:
    name: sharedSG1
    description: ''
    author: rohitjain+25@simpledatalabs.com
    language: scala
    artefactID: ''
    createdAt: '2022-12-15 18:13:14'
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
artefactID: BaseProjectExt3
