---
version: 2
models:
- name: "customers"
  description: "This table has basic information about a customer, as well as some\
    \ derived facts based on a customer's orders"
  columns:
  - name: "customer_id"
    description: "This is a unique identifier for a customer"
    tests:
    - "unique"
    - "not_null"
  - name: "first_name"
    description: "Customer's first name. PII."
  - name: "last_name"
    description: "Customer's last name. PII."
  - name: "first_order"
    description: "Date (UTC) of a customer's first order"
  - name: "most_recent_order"
    description: "Date (UTC) of a customer's most recent order"
  - name: "number_of_orders"
    description: "Count of the number of orders a customer has placed"
  - name: "total_order_amount"
    description: "Total value (AUD) of a customer's orders"
- name: "orders"
  description: "This table has basic information about orders, as well as some derived\
    \ facts based on payments"
  columns:
  - name: "order_id"
    dataType:
      type: "Integer"
  - name: "customer_id"
    dataType:
      type: "Integer"
  - name: "order_date"
    dataType:
      type: "Date"
  - name: "status"
    dataType:
      type: "String"
  - name: "credit_card_amount"
    dataType:
      type: "Double"
  - name: "coupon_amount"
    dataType:
      type: "Double"
  - name: "bank_transfer_amount"
    dataType:
      type: "Double"
  - name: "gift_card_amount"
    dataType:
      type: "Double"
  - name: "amount"
    dataType:
      type: "Double"
  - name: "extra_column"
    dataType:
      type: "Integer"
- name: "new_model"
  columns:
  - name: "id"
    dataType:
      type: "Integer"
  - name: "first_name"
    dataType:
      type: "String"
  - name: "last_name"
    dataType:
      type: "String"
