name: ApplicationProjectExt2
description: ''
version: 0.0.1
author: rohitjain+27@simpledatalabs.com
language: scala
buildSystem: ''
buildSystemDetails:
  packageName: ApplicationProjectExt2
  buildSystem: maven
  author: null
  createdAt: '2022-12-15 18:02:27'
pipelines:
  pipelines/Pipeline1:
    name: Pipeline1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2022-12-15 18:03:09'
    datasets:
      inputs:
      - datasets/d1
      outputs:
      - datasets/d2
    subgraphs: []
    dependencies: {}
datasets:
  datasets/d1:
    name: d1
    description: ''
    author: rohitjain+27@simpledatalabs.com
    createdAt: '2022-12-15 18:03:33'
    physicalDatasets:
      dev:
        fabricId: 52
        datasetType: File
        description: ''
        author: rohitjain+27@simpledatalabs.com
        createdAt: '2022-12-15 18:03:33'
  datasets/d2:
    name: d2
    description: ''
    author: rohitjain+27@simpledatalabs.com
    createdAt: '2022-12-15 18:04:05'
    physicalDatasets:
      dev:
        fabricId: 52
        datasetType: File
        description: ''
        author: rohitjain+27@simpledatalabs.com
        createdAt: '2022-12-15 18:04:05'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2022-12-15 18:02:27'
  gems: {}
  udfs:
    udfs/square:
      name: square
      description: ''
      tags:
      - ''
      inputs:
      - ''
      outputs:
      - ''
      author: rohitjain+27@simpledatalabs.com
      createdAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies:
  '192':
    projectUID: 192
    projectName: BaseProjectExt3
    repositoryPath: gitUri=https://github.com/aarjay00/prophecyTest&subPath=baseProjectExt3
    version: BaseProjectExt3/1.0
    author: null
    createdAt: '2022-12-15 18:14:59'
pipelineConfigurations: {}
artefactID: ApplicationProjectExt2
