---
version: 2
models:
- name: "model1"
  columns:
  - name: "id"
    dataType:
      type: "Integer"
  - name: "first_name"
    dataType:
      type: "String"
  - name: "last_name"
    dataType:
      type: "String"
  tests: []
